import localFont from "next/font/local";
import "./globals.css";
import Loading from "./loading";
import { Suspense } from "react";
import CommonLayout from "@/components/ui/common-layout";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const clerkPublishableKey =process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;

if (!clerkPublishableKey) {
  throw new Error("Missing Clerk publishable key");
}
export default function RootLayout({ children }) {
  return (
  <ClerkProvider publishableKey={clerkPublishableKey} afterSignOutUrl="/">
      <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={<Loading/>}>
        <CommonLayout children={children}/>
        </Suspense>
      </body>
    </html>
  </ClerkProvider>
  );
}
